### ISSUE TITLE
Walkthrough is incorrect - no longer works

### ISSUE THREAD

**Issue by XcrigX** [cqframework/cqf-ccc#4]
I'm trying to use the walkthrough to test out the CQF server here: 
https://github.com/cqframework/cqf-ccc/blob/master/WALKTHROUGH.md

A couple of problems: 

Firstly, it references the ColorectalCancerScreeningCDS-bundle at this location: 
https://github.com/cqframework/cqf-ccc/blob/master/bundles/plandefinition/ColorectalCancerScreeningCDS-bundle.json

But it appears to have moved to here:
https://github.com/cqframework/cqf-ccc/blob/master/bundles/plandefinition/ColorectalCancerScreeningCDS/ColorectalCancerScreeningCDS-bundle.json

Secondly, the example says to run the Measure/$evaluate-measure operation, but the bundle contains no Measure resources and running it results in an error: 
"diagnostics": "HAPI-2001: Resource Measure/ColorectalCancerScreeningCQM is not known"

EDIT: to be clear, I'm not running the full example. Rather I've stood up my own CQF instance (from the docker alphora/cqf-ruler), posted the example bundle to it, and an trying to run the evaluate-measure operation against my instance.

**Comment by bryantaustin13** [comment]
I am a bit confused. I see the bundle at:
https://github.com/cqframework/cqf-ccc/blob/master/bundles/plandefinition/ColorectalCancerScreeningCDS/ColorectalCancerScreeningCDS-bundle.json
Which is the location listed in the Walk Through:
curl -d "@bundles/plandefinition/ColorectalCancerScreeningCDS/ColorectalCancerScreeningCDS-bundle.json" -H "Content-Type: application/json" -X POST https://cloud.alphora.com/sandbox/r4/cds/fhir

***The measure listed in the $evaluate-measure command is /Measure/ColorectalCancerScreeningCQM.
I am betting that you would have to explicitly post that measure to the server you are using. It already exists on https://cloud.alphora.com/sandbox/r4/cds/fhir

The following is representative of explicitly doing the steps in the Walk Through:
Next if I use the curl command to run $evaluate-measure from the command line:
curl 'https://cloud.alphora.com/sandbox/r4/cqm/fhir/Measure/ColorectalCancerScreeningCQM/$evaluate-measure?patient=denom-EXM130&periodStart=2022-01-01&periodEnd=2022-12-31' -H "Content-Type: application/json"

I get a MeasureReport:
(First few lines)
{
  "resourceType": "MeasureReport",
  "language": "en",
  "extension": [ {
    "url": "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description",
    "valueString": "Percentage of adults 50-75 years of age who had appropriate screening for colorectal cancer"
  } ],
  "status": "complete",
  ...
  
  In Postman, if I run the command:
  https://cloud.alphora.com/sandbox/r4/cqm/fhir/Measure/ColorectalCancerScreeningCQM/$evaluate-measure?patient=denom-EXM130&periodStart=2022-01-01&periodEnd=2022-12-31
  I also get a MeasureReport.

**Comment by XcrigX** [comment]
RE: missing bundle. In the instructions under this section:
https://github.com/cqframework/cqf-ccc/blob/master/WALKTHROUGH.md#running-the-decision-support

The link to the bundle gives me a 404. 
This is the line of code:
https://github.com/cqframework/cqf-ccc/blob/master/WALKTHROUGH.md?plain=1#L125

I think the link is just wrong. 
instead of "bundles/plandefinition/ColorectalCancerScreeningCDS-bundle.json"
it should be "bundles/plandefinition/ColorectalCancerScreeningCDS/ColorectalCancerScreeningCDS-bundle.json"

**Comment by XcrigX** [comment]
.. appreciate you looking at it. It's been a while since I tried this so my memory is fuzzy.  Perhaps I was expecting that the Measure resource would also be included in the provided sample bundle so everything needed to run walkthrough was in there.

**Comment by bryantaustin13** [comment]
![Screenshot 2024-03-06 at 10 44 36 AM](https://github.com/cqframework/cqf-ccc/assets/3997736/755eb4e0-826c-482d-a446-5008bca6e780)
The complete line for the curl is:
curl -d "@bundles/plandefinition/ColorectalCancerScreeningCDS/ColorectalCancerScreeningCDS-bundle.json" -H "Content-Type: application/json" -X POST https://cloud.alphora.com/sandbox/r4/cds/fhir

Could you have been using an older WalkThrough?

**Comment by XcrigX** [comment]
I'm saying - if you try to click the link in blue (ColorectalCancerScreeningCDS) two lines above the curl command to download the bundle, it links to the wrong location. 
The curl command itself, if run from the relative directory provably works.  I was trying to download the Bundle to POST it to my sever via Postman, and had to manually go find it in the subdirectory of the repo.

**Comment by bryantaustin13** [comment]
I am so sorry. You are completely correct. That link is wrong. I missed it. We will adjust that. Thank you for pointing it out.

**Comment by bryantaustin13** [comment]
PR: https://github.com/cqframework/cqf-ccc/pull/5#issue-2174679213
